/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProduitsRouteImport } from './routes/produits'
import { Route as PersonnalisationRouteImport } from './routes/personnalisation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduitsProductIdRouteImport } from './routes/produits.$productId'

const ProduitsRoute = ProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonnalisationRoute = PersonnalisationRouteImport.update({
  id: '/personnalisation',
  path: '/personnalisation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsProductIdRoute = ProduitsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProduitsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/personnalisation': typeof PersonnalisationRoute
  '/produits': typeof ProduitsRouteWithChildren
  '/produits/$productId': typeof ProduitsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/personnalisation': typeof PersonnalisationRoute
  '/produits': typeof ProduitsRouteWithChildren
  '/produits/$productId': typeof ProduitsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/personnalisation': typeof PersonnalisationRoute
  '/produits': typeof ProduitsRouteWithChildren
  '/produits/$productId': typeof ProduitsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/personnalisation'
    | '/produits'
    | '/produits/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/personnalisation'
    | '/produits'
    | '/produits/$productId'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/personnalisation'
    | '/produits'
    | '/produits/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  PersonnalisationRoute: typeof PersonnalisationRoute
  ProduitsRoute: typeof ProduitsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/produits': {
      id: '/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personnalisation': {
      id: '/personnalisation'
      path: '/personnalisation'
      fullPath: '/personnalisation'
      preLoaderRoute: typeof PersonnalisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/$productId': {
      id: '/produits/$productId'
      path: '/$productId'
      fullPath: '/produits/$productId'
      preLoaderRoute: typeof ProduitsProductIdRouteImport
      parentRoute: typeof ProduitsRoute
    }
  }
}

interface ProduitsRouteChildren {
  ProduitsProductIdRoute: typeof ProduitsProductIdRoute
}

const ProduitsRouteChildren: ProduitsRouteChildren = {
  ProduitsProductIdRoute: ProduitsProductIdRoute,
}

const ProduitsRouteWithChildren = ProduitsRoute._addFileChildren(
  ProduitsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  PersonnalisationRoute: PersonnalisationRoute,
  ProduitsRoute: ProduitsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
